### ISSUE TITLE
Comments not saved

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/Apollo#1]
When leaving comments in popup window for any feature in Apollo, these would not be saved properly. Even if typed, then the mouse was clicked off to 'save', and the window was closed then re-opened, then the comments would not be present. This was a common complaint for students in BICH464. 

It is a known issue for overlapping features. 

It may also be triggered when leaving comments with special characters.

**Comment by hexylena** [comment]
Back in my day... I definitely remember it happening due to special chars. We just told students not to use those but that's a terrible solution and there's no excuse for utf8 problems in 2018. That whole interface is way too finicky about saving stuff, it's not great. :(

**Comment by MoffMade** [comment]
Comments saved through annotation panel now, this didn't occur in spot testing but I think it's sorted now? May need to test special characters still.

**Comment by jrr-cpt** [comment]
Many special characters are now saving in the comments.
