### ISSUE TITLE
Right-click menu options order

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/Apollo#2]
Right-clicking on a gene feature in Apollo to edit the annotation and you see 
 
![apollo menu options naming and order](https://user-images.githubusercontent.com/38894438/43998270-84e73592-9db7-11e8-9492-f178c6be0b34.png)

The order should be shuffled so that Edit Information is closer to the top. If the Edit Information option can be renamed to something that sounds more like 'make annotation' and helps people realize that is the one to click (rather than CPT GO Annotation), that would also be helpful.

**Comment by MoffMade** [comment]
This option is changed to "Open Annotation" and has been moved to be immediately after "Get Sequence", "Get GFF3", and "Zoom to Base Level" with 2.6.1
![image](https://user-images.githubusercontent.com/5633348/91754888-d2572a80-eb8f-11ea-8b5b-a3d55c0933d0.png)
