### ISSUE TITLE
Boundaries cannot be dragged on Genes called from Sixpack

### ISSUE THREAD

**Issue by MoffMade** [TAMU-CPT/Apollo#6]
When attempting to move the boundaries for any gene feature called from the Sixpack evidence track, nothing occurs visually and the following error message is in the logs.

>2018-11-02 21:08:38,135 [clientInboundChannel-1] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
>java.lang.reflect.InvocationTargetException
>	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5$_closure6.doCall(AnnotationEditorController.groovy:1144)
>	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5.doCall(AnnotationEditorController.groovy:1143)
>	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4.doCall(AnnotationEditorController.groovy:1139)
>	at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
>	at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>	at java.lang.Thread.run(Thread.java:748)
>Caused by: java.lang.NullPointerException: Cannot get property 'id' on null object
>	at org.bbop.apollo.FeatureService.$tt__convertFeatureToJSON(FeatureService.groovy:1686)
>	at org.bbop.apollo.RequestHandlingService._do_setExonBoundaries(RequestHandlingService.groovy:1018)
>	... 8 more

**Comment by MoffMade** [comment]
JBrowese Instance for the organism that triggered the error message above: 
[Lorac-Test2-Jbrowse.zip](https://github.com/TAMU-CPT/Apollo/files/2544171/Lorac-Test2-Jbrowse.zip)

**Comment by nathandunn** [comment]
I was able to very quickly reproduce this locally on 2.2.0 . . . specifically with the 6-pack evidence.  Will let you know shortly what I think is up.

**Comment by nathandunn** [comment]
Structure: 

```
##gff-version 3
##sequence-region Lorac 1 43147
Lorac	.	gene	10509	12842	.	+	.	owner=ndunn@me.com;ID=0e1f9998-538d-4c53-aae7-bfede47d5152;date_last_modified=2018-12-14;Name=CDS.0.1231_0.337942526641;date_creation=2018-12-14
Lorac	.	mRNA	10509	12842	.	+	.	owner=ndunn@me.com;Parent=0e1f9998-538d-4c53-aae7-bfede47d5152;ID=03a108e1-2184-4ec1-a250-39d47671ee4f;date_last_modified=2018-12-14;Name=CDS.0.1231_0.337942526641-00001;date_creation=2018-12-14
Lorac	.	CDS	10509	12842	.	+	0	Parent=03a108e1-2184-4ec1-a250-39d47671ee4f;ID=03a108e1-2184-4ec1-a250-39d47671ee4f-CDS;Name=03a108e1-2184-4ec1-a250-39d47671ee4f-CDS
Lorac	.	exon	10509	12842	.	+	.	Parent=03a108e1-2184-4ec1-a250-39d47671ee4f;ID=61919699-c315-4778-8293-1227a406de8e;Name=61919699-c315-4778-8293-1227a406de8e
###
```

**Comment by nathandunn** [comment]
We get a valid exon here:

```
      Exon exon = Exon.findByUniqueName(locationCommand.getString(FeatureStringEnum.UNIQUENAME.value))
```
But then it returns a null transcript:
```
     Transcript transcript = exonService.getTranscript(exon)
```

**Comment by nathandunn** [comment]
@MoffMade  So, I think its having problems because the feature structure is gene-mRNA. 

Working structures are:
- gene (top) -> exon/CDS
- mRNA->exon/CDS

For some reason when calling the parent on exon, instead of bringing back the mRNA, it brings back itself. 

The short-term fix is to change the structure of the evidence. 

Longer term fix is https://github.com/GMOD/Apollo/issues/1992 as I feel like annotations off of this type of evidence should be allowed.

**Comment by MoffMade** [comment]
You mean the working structure of the evidence itself? I'll update the sixpack tool to leave out the mRNA entry and leave it at gene->CDS then and see what happens.

**Comment by nathandunn** [comment]
@MoffMade  was there any progress on this?

**Comment by MoffMade** [comment]
We are using a toolshed tool for the naive ORF calling (sixpack) so I added in a tool that should strip the mRNA features from the model before adding them into jBrowse. Testing to see if that solves anything now.

**Comment by MoffMade** [comment]
@nathandunn it does look like stripping the mRNA out and leaving the Gene -> CDS/Exon model worked. The called features from this new track could be dragged/moved around like normal.

**Comment by nathandunn** [comment]
@MoffMade  can this and https://github.com/GMOD/Apollo/issues/1992 be closed now?
